# Generated by Django 5.2.3 on 2025-06-18 20:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=155, verbose_name="Ονομα")),
                ("last_name", models.CharField(max_length=155, verbose_name="Επίθετο")),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=155, null=True, verbose_name="Οντότητα"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Wrong email Format.",
                                regex="([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\\.[A-Z|a-z]{2,})+",
                            )
                        ],
                        verbose_name="Email",
                    ),
                ),
                (
                    "tin_number",
                    models.CharField(
                        blank=True,
                        max_length=9,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Το ΑΦΜ πρέπει να έχει 9 ψηφία.",
                                regex="^\\d{9}$",
                            )
                        ],
                        verbose_name="ΑΦΜ",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Το τηλέφωνο πρέπει να έχει 10 ψηφία.",
                                regex="^\\d{10}$",
                            )
                        ],
                        verbose_name="Τηεφωνο",
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, null=True, verbose_name="Πληροφορίες"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Χρήστης",
                    ),
                ),
            ],
            options={
                "verbose_name": "Επαφή",
                "verbose_name_plural": "Επαφές",
                "unique_together": {("first_name", "last_name", "company", "user")},
            },
        ),
    ]
