# Generated by Django 5.2.3 on 2025-06-11 10:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=155, verbose_name='Ονομα')),
                ('last_name', models.CharField(max_length=155, verbose_name='Επίθετο')),
                ('father_name', models.CharField(blank=True, max_length=155, null=True, verbose_name='Πατρώνυμο')),
                ('tin_number', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='Το ΑΦΜ πρέπει να έχει 9 ψηφία.', regex='^\\d{9}$')], verbose_name='ΑΦΜ')),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Το τηλέφωνο πρέπει να έχει 10 ψηφία.', regex='^\\d{10}$')], verbose_name='Τηεφωνο')),
            ],
            options={
                'verbose_name': 'Αγροτης',
                'verbose_name_plural': 'Αγροτες',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('ΤΗΛΕΦΩΝΟ', 'ΤΗΛΕΦΩΝΟ'), ('ΑΥΤΟΠΡΟΣΩΠΑ', 'ΑΥΤΟΠΡΟΣΩΠΑ'), ('EMAIL', 'EMAIL'), ('ΕΓΓΡΑΦΟ', 'ΕΓΓΡΑΦΟ'), ('ΑΛΛΟ', 'ΑΛΛΟ')], max_length=20, verbose_name='Μεθοδος Επικοινωνίας')),
                ('subject', models.CharField(max_length=255, verbose_name='Θεμα')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='Περιληψη')),
                ('status', models.CharField(choices=[('ΑΝΟΙΧΤΟ', 'ΑΝΟΙΧΤΟ'), ('ΣΕ_ΕΞΕΛΙΞΗ', 'ΣΕ ΕΞΕΛΙΞΗ'), ('ΟΛΟΚΛΗΡΩΘΗΚΕ', 'ΟΛΟΚΛΗΡΩΘΗΚΕ'), ('ΚΛΕΙΣΤΟ', 'ΚΛΕΙΣΤΟ')], default='ΑΝΟΙΧΤΟ', max_length=20, verbose_name='Κατασταση')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='notes.customer')),
            ],
            options={
                'verbose_name': 'Σημειωση',
                'verbose_name_plural': 'Σημειωσεις',
                'ordering': ['-created'],
            },
        ),
    ]
