# Generated by Django 5.2.3 on 2025-06-13 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης'),
        ),
        migrations.AlterField(
            model_name='note',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='notes.customer', verbose_name='Πελάτης'),
        ),
        migrations.AlterField(
            model_name='note',
            name='method',
            field=models.CharField(choices=[('ΤΗΛΕΦΩΝΟ', 'ΤΗΛΕΦΩΝΟ'), ('ΑΥΤΟΠΡΟΣΩΠΑ', 'ΑΥΤΟΠΡΟΣΩΠΑ'), ('EMAIL', 'EMAIL'), ('ΕΓΓΡΑΦΟ', 'ΕΓΓΡΑΦΟ'), ('ΑΛΛΟ', 'ΑΛΛΟ')], max_length=20, verbose_name='Επικοινωνία'),
        ),
    ]
