# Generated by Django 5.2.3 on 2025-06-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_customer_user_note_user_alter_note_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="status",
            field=models.CharField(
                choices=[
                    ("ΑΝΟΙΧΤΟ", "ΑΝΟΙΧΤΟ"),
                    ("ΣΕ ΕΞΕΛΙΞΗ", "ΣΕ ΕΞΕΛΙΞΗ"),
                    ("ΚΛΕΙΣΤΟ", "ΚΛΕΙΣΤΟ"),
                ],
                default="ΑΝΟΙΧΤΟ",
                max_length=20,
                verbose_name="Κατασταση",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="subject",
            field=models.CharField(
                choices=[
                    ("ΑΝΟΙΧΤΟ", "ΑΝΟΙΧΤΟ"),
                    ("ΣΕ ΕΞΕΛΙΞΗ", "ΣΕ ΕΞΕΛΙΞΗ"),
                    ("ΚΛΕΙΣΤΟ", "ΚΛΕΙΣΤΟ"),
                ],
                max_length=255,
                verbose_name="Θεμα",
            ),
        ),
    ]
