# Generated by Django 5.2.3 on 2025-06-13 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_alter_note_status_alter_note_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="subject",
            field=models.CharField(
                choices=[
                    ("ΑΛΛΟ", "ΑΛΛΟ"),
                    ("Πληρωμή", "Πληρωμή"),
                    ("Αρδευτική Ενημερότητα", "Αρδευτική Ενημερότητα"),
                    ("Εύρεση Αγροτεμαχίου", "Εύρεση Αγροτεμαχίου"),
                    ("Λογαριασμός", "Λογαριασμός"),
                    ("Τιμολόγιο", "Τιμολόγιο"),
                    ("Ενημέρωση", "Ενημέρωση"),
                    ("Αποζημίωση", "Αποζημίωση"),
                ],
                max_length=255,
                verbose_name="Θεμα",
            ),
        ),
    ]
