# Generated by Django 5.2.3 on 2025-06-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_alter_note_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="completed",
            field=models.BooleanField(default=False, verbose_name="ολοκληρωθηκε"),
        ),
    ]
