# Generated by Django 5.2.3 on 2025-06-15 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_note_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="summary",
            field=models.CharField(
                blank=True, max_length=240, null=True, verbose_name="ΠΛηροφορίες"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notes",
                to="notes.customer",
                verbose_name="Επαφή",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="method",
            field=models.CharField(
                choices=[
                    ("Τηλέφωνο", "Τηλέφωνο"),
                    ("Γραφείο", "Γραφείο"),
                    ("Email", "Email"),
                    ("Έγγραφο", "Έγγραφο"),
                    ("Άλλο", "Άλλο"),
                ],
                default="Γραφείο",
                max_length=20,
                verbose_name="Επικοινωνία",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ανοιχτό", "Ανοιχτό"),
                    ("Σε Εξέλιξη", "Σε Εξέλιξη"),
                    ("Κλειστό", "Κλειστό"),
                ],
                default="ΑΝΟΙΧΤΟ",
                max_length=20,
                verbose_name="Κατασταση",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="subject",
            field=models.CharField(
                choices=[
                    ("Άλλο", "Άλλο"),
                    ("Πληρωμή", "Πληρωμή"),
                    ("Αρδευτική Ενημερότητα", "Αρδευτική Ενημερότητα"),
                    ("Εύρεση Αγροτεμαχίου", "Εύρεση Αγροτεμαχίου"),
                    ("Λογαριασμός", "Λογαριασμός"),
                    ("Τιμολόγιο", "Τιμολόγιο"),
                    ("Ενημέρωση", "Ενημέρωση"),
                    ("Αποζημίωση", "Αποζημίωση"),
                ],
                default="Άλλο",
                max_length=255,
                verbose_name="Θεμα",
            ),
        ),
    ]
