# Generated by Django 5.2.3 on 2025-06-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_customer_summary_alter_note_customer_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("first_name", "last_name", "father_name")},
        ),
    ]
