# Generated by Django 5.2.3 on 2025-06-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0007_alter_customer_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="shortcode",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="status",
            field=models.CharField(
                choices=[
                    ("Ανοιχτό", "Ανοιχτό"),
                    ("Σε Εξέλιξη", "Σε Εξέλιξη"),
                    ("Κλειστό", "Κλειστό"),
                ],
                default="Ανοιχτό",
                max_length=20,
                verbose_name="Κατασταση",
            ),
        ),
    ]
