# Generated by Django 5.2.3 on 2025-06-16 18:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0008_note_shortcode_alter_note_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "Επαφή", "verbose_name_plural": "Επαφές"},
        ),
        migrations.AlterUniqueTogether(
            name="customer",
            unique_together={("first_name", "last_name", "father_name", "user")},
        ),
    ]
