# Generated by Django 5.2.3 on 2025-06-16 19:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0009_alter_customer_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Customer",
            new_name="Contact",
        ),
        migrations.RenameField(
            model_name="note",
            old_name="customer",
            new_name="contact",
        ),
    ]
