# Generated by Django 5.2.3 on 2025-06-17 20:42

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0010_rename_customer_contact_rename_customer_note_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("first_name", "last_name", "user")},
        ),
        migrations.AddField(
            model_name="contact",
            name="company",
            field=models.CharField(
                blank=True, max_length=155, null=True, verbose_name="Οντότητα"
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Wrong email Format.",
                        regex="([A-Za-z0-9]+[.-_])*[A-Za-z0-9]+@[A-Za-z0-9-]+(\\.[A-Z|a-z]{2,})+",
                    )
                ],
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="summary",
            field=models.CharField(
                blank=True, max_length=240, null=True, verbose_name="Πληροφορίες"
            ),
        ),
        migrations.RemoveField(
            model_name="contact",
            name="father_name",
        ),
    ]
