# Generated by Django 5.2.3 on 2025-06-17 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0011_alter_contact_unique_together_contact_company_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="contact",
            unique_together={("first_name", "last_name", "company", "user")},
        ),
    ]
