# Generated by Django 5.2.3 on 2025-06-18 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0012_alter_contact_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="summary",
            field=models.TextField(blank=True, null=True, verbose_name="Πληροφορίες"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="tin_number",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Το ΑΦΜ πρέπει να έχει 9 ψηφία.", regex="^\\d{9}$"
                    )
                ],
                verbose_name="ΑΦΜ",
            ),
        ),
    ]
