# Generated by Django 5.2.3 on 2025-06-18 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
        ("notes", "0013_alter_contact_summary_alter_contact_tin_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notes",
                to="contact.contact",
                verbose_name="Επαφή",
            ),
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
