# Generated by Django 5.2.3 on 2025-06-18 23:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
        ("notes", "0014_alter_note_contact_delete_contact"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="note",
            index=models.Index(fields=["user"], name="notes_note_user_id_2efe7b_idx"),
        ),
        migrations.AddIndex(
            model_name="note",
            index=models.Index(
                fields=["contact"], name="notes_note_contact_18b3e0_idx"
            ),
        ),
    ]
