# Generated by Django 5.2.3 on 2025-06-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bg_body", models.CharField(blank=True, max_length=10, null=True)),
                ("bg_navbar", models.CharField(blank=True, max_length=10, null=True)),
                ("bg_note", models.CharField(blank=True, max_length=10, null=True)),
                ("text_note", models.CharField(blank=True, max_length=10, null=True)),
                ("text_body", models.CharField(blank=True, max_length=10, null=True)),
                ("text_navbar", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
