# Generated by Django 5.2.3 on 2025-06-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaltheme",
            name="bg_form",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
